name: Fyntrac Test Runner

on:
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SPRING_DATA_MONGODB_URI: mongodb://root:R3s3rv%23313@72.60.172.224/TNT001?authSource=admin

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Show Mongo URI env var
        run: echo "Mongo URI: $SPRING_DATA_MONGODB_URI"

      - name: Check MongoDB connectivity
        run: |
          echo "Checking MongoDB connection to 72.60.172.224:27017"
          nc -vz 72.60.172.224 27017

      - name: Run TestIFRS9
        continue-on-error: true
        run: ./gradlew clean test --tests "com.fyntrac.data.testdriver.ExcelTestDriver" -PtestData=TestIFRS9 -Dspring.data.mongodb.uri="$SPRING_DATA_MONGODB_URI" --no-daemon --info

      - name: Run TestRevenue
        continue-on-error: true
        run: ./gradlew test --tests "com.fyntrac.data.testdriver.ExcelTestDriver" -PtestData=TestRevenue -Dspring.data.mongodb.uri="$SPRING_DATA_MONGODB_URI" --no-daemon --info

      - name: Run TestSBO
        continue-on-error: true
        run: ./gradlew test --tests "com.fyntrac.data.testdriver.ExcelTestDriver" -PtestData=TestSBO -Dspring.data.mongodb.uri="$SPRING_DATA_MONGODB_URI" --no-daemon --info

      - name: Run TestGFO
        continue-on-error: true
        run: ./gradlew test --tests "com.fyntrac.data.testdriver.ExcelTestDriver" -PtestData=TestGFO -Dspring.data.mongodb.uri="$SPRING_DATA_MONGODB_URI" --no-daemon --info

      - name: Publish Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: junit-test-results
          path: build/test-results/test

      - name: Test Summary
        uses: test-summary/action@v2
        if: always()
        with:
          paths: build/test-results/test/*.xml
